In [3]:
import pandas as pd
import numpy as np

# Loading Dataset

In [4]:
interactions = pd.read_csv("processed_interactions.csv")
interactions[["user_id", "business_id", "stars", "date"]].head()

                  user_id             business_id  stars                 date
0  -FxsSuwDbIII7yo5BjHpiA  sr-5EY6bmp4jINhea06MjA      4  2016-06-15 18:24:36
1  -FxsSuwDbIII7yo5BjHpiA  Gf1EboxqdJ9SPsVJur93Cw      4  2016-08-26 14:06:32
2  -FxsSuwDbIII7yo5BjHpiA  yeHLiKNp0hyR-ig4M6us-w      5  2016-11-22 15:26:03
3  -FxsSuwDbIII7yo5BjHpiA  5FDt7sy-70y4_37Dh2qcbw      4  2017-03-15 19:41:39
4  -FxsSuwDbIII7yo5BjHpiA  3y61A28PQDZ4weeeTRfIlA      3  2017-10-05 20:55:17

Rating thresholding (matches Section 4.2.5)

In [5]:
interactions["label"] = (interactions["stars"] >= 3).astype(int)

Temporal Sorting

In [6]:
interactions["date"] = pd.to_datetime(interactions["date"])
interactions = interactions.sort_values(["user_id", "date"])

Ratio-based per-user split (80/10/10), matching Section 4.4 to 4.4.2

In [7]:
def split_user(df):
    n = len(df)
    train_end = int(0.8 * n)
    val_end = int(0.9 * n)
    
    return (
        df.iloc[:train_end],
        df.iloc[train_end:val_end],
        df.iloc[val_end:]
    )

train, val, test = [], [], []

for _, user_df in interactions.groupby("user_id"):
    if len(user_df) < 5:
        continue
    tr, va, te = split_user(user_df)
    train.append(tr)
    val.append(va)
    test.append(te)

train_df = pd.concat(train)
val_df = pd.concat(val)
test_df = pd.concat(test)

In [8]:
print("Users:", train_df["user_id"].nunique())
print("Items:", train_df["business_id"].nunique())
print("Interactions:", len(train_df))
print("Avg interactions/user:", len(train_df) / train_df["user_id"].nunique())

Users: 413
Items: 866
Interactions: 2044
Avg interactions/user: 4.9491525423728815

In [14]:
import sys
sys.version

'3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]'

In [2]:
from recommenders.models.ncf.ncf_singlenode import NCF
from recommenders.evaluation.python_evaluation import (
    precision_at_k,
    recall_at_k,
    ndcg_at_k
)

print("NeuCF imports OK")

WARNING:tensorflow:From c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\recommenders\models\ncf\ncf_singlenode.py:12: The name tf.disable_eager_execution is deprecated. Please use tf.compat.v1.disable_eager_execution instead.

NeuCF imports OK

In [9]:
def to_recommenders_format(df):
    return df.rename(columns={
        "user_id": "userID",
        "business_id": "itemID",
        "label": "label",
        "date": "timestamp"
    })[["userID", "itemID", "label", "timestamp"]]

train_rec = to_recommenders_format(train_df)
val_rec   = to_recommenders_format(val_df)
test_rec  = to_recommenders_format(test_df)

# Matching hyperparameters exactly

## GMF

In [20]:
# Create mappings from training data
user2id = {u: i for i, u in enumerate(train_df["user_id"].unique())}
item2id = {i: j for j, i in enumerate(train_df["business_id"].unique())}

In [21]:
def apply_mapping(df, user2id, item2id):
    df = df.copy()
    df["userID"] = df["user_id"].map(user2id)
    df["itemID"] = df["business_id"].map(item2id)
    return df.dropna(subset=["userID", "itemID"])

In [22]:
train_rec = apply_mapping(train_df, user2id, item2id)
val_rec   = apply_mapping(val_df, user2id, item2id)
test_rec  = apply_mapping(test_df, user2id, item2id)

train_rec["userID"] = train_rec["userID"].astype(int)
train_rec["itemID"] = train_rec["itemID"].astype(int)
val_rec["userID"]   = val_rec["userID"].astype(int)
val_rec["itemID"]   = val_rec["itemID"].astype(int)
test_rec["userID"]  = test_rec["userID"].astype(int)
test_rec["itemID"]  = test_rec["itemID"].astype(int)

In [23]:
train_rec[["userID", "itemID", "label"]].to_csv("train.csv", index=False)
val_rec[["userID", "itemID", "label"]].to_csv("val.csv", index=False)
test_rec[["userID", "itemID", "label"]].to_csv("test.csv", index=False)

In [33]:
from recommenders.models.ncf.dataset import Dataset

dataset = Dataset(
    train_file="train.csv",
    test_file="test.csv",      # optional but recommended
    col_user="userID",
    col_item="itemID",
    col_rating="label",
    binary=True,
    n_neg=4,                   # default in NCF paper
    n_neg_test=100,             # standard for evaluation
    seed=42
)

INFO:recommenders.models.ncf.dataset:Indexing train.csv ...
INFO:recommenders.models.ncf.dataset:Indexing test.csv ...
INFO:recommenders.models.ncf.dataset:Creating full leave-one-out test file test_full.csv ...
  0%|          | 0/280 [00:00<?, ?it/s]c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
 10%|█         | 29/280 [00:00<00:00, 289.96it/s]c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
 22%|██▏       | 62/280 [00:00<00:00, 311.69it/s]c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [34]:
dataset.n_users
dataset.n_items

866

In [46]:
from recommenders.models.ncf.ncf_singlenode import NCF

gmf_dir = "checkpoints/gmf"

gmf = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="GMF",
    n_factors=1024,
    learning_rate=1e-3,
    batch_size=8192,
    n_epochs=100,
    verbose=1,
    seed=42
)

gmf.fit(dataset)
gmf.save(gmf_dir)

c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1697: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 1 [0.47s]: train_loss = 0.693146
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 2 [0.56s]: train_loss = 0.693143
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 3 [0.40s]: train_loss = 0.693138
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 4 [0.41s]: train_loss = 0.693134
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 5 [0.48s]: train_loss = 0.693128
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 6 [1.14s]: train_loss = 0.693121
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 7 [1.25s]: train_loss = 0.693114
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 8 [1.17s]: train_loss = 0.693107
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 9 [1.06s]: train_loss = 0.693099
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 10 [0.45s]: train_loss = 0.693089
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 11 [0.71s]: train_loss = 0.693078
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 12 [0.43s]: train_loss = 0.693067
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 13 [0.43s]: train_loss = 0.693056
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 14 [0.42s]: train_loss = 0.693043
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 15 [0.54s]: train_loss = 0.693027
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 16 [0.54s]: train_loss = 0.693014
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 17 [0.43s]: train_loss = 0.692997
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 18 [0.52s]: train_loss = 0.692977
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 19 [0.46s]: train_loss = 0.692954
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 20 [0.56s]: train_loss = 0.692930
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 21 [0.41s]: train_loss = 0.692906
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 22 [0.41s]: train_loss = 0.692872
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 23 [0.39s]: train_loss = 0.692838
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 24 [0.41s]: train_loss = 0.692796
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 25 [0.39s]: train_loss = 0.692755
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 26 [0.39s]: train_loss = 0.692706
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 27 [0.43s]: train_loss = 0.692648
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 28 [0.40s]: train_loss = 0.692579
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 29 [0.52s]: train_loss = 0.692511
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 30 [0.42s]: train_loss = 0.692422
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 31 [0.39s]: train_loss = 0.692328
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 32 [0.38s]: train_loss = 0.692201
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 33 [0.39s]: train_loss = 0.692087
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 34 [0.48s]: train_loss = 0.691945
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 35 [0.39s]: train_loss = 0.691770
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 36 [0.58s]: train_loss = 0.691585
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 37 [0.42s]: train_loss = 0.691362
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 38 [0.40s]: train_loss = 0.691093
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 39 [0.56s]: train_loss = 0.690823
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 40 [0.37s]: train_loss = 0.690493
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 41 [0.39s]: train_loss = 0.690150
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 42 [0.39s]: train_loss = 0.689723
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 43 [0.40s]: train_loss = 0.689264
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 44 [0.41s]: train_loss = 0.688762
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 45 [0.40s]: train_loss = 0.688179
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 46 [0.40s]: train_loss = 0.687460
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 47 [0.39s]: train_loss = 0.686811
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 48 [0.40s]: train_loss = 0.685858
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 49 [0.54s]: train_loss = 0.685018
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 50 [0.39s]: train_loss = 0.683959
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 51 [0.39s]: train_loss = 0.682857
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 52 [0.39s]: train_loss = 0.681635
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 53 [0.40s]: train_loss = 0.680243
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 54 [0.38s]: train_loss = 0.678726
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 55 [0.38s]: train_loss = 0.677104
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 56 [0.39s]: train_loss = 0.675394
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 57 [0.40s]: train_loss = 0.673505
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 58 [0.53s]: train_loss = 0.671223
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 59 [0.39s]: train_loss = 0.668652
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 60 [0.38s]: train_loss = 0.666478
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 61 [0.38s]: train_loss = 0.663886
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 62 [0.38s]: train_loss = 0.661122
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 63 [0.38s]: train_loss = 0.657714
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 64 [0.55s]: train_loss = 0.654431
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 65 [0.55s]: train_loss = 0.650917
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 66 [0.49s]: train_loss = 0.646992
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 67 [0.56s]: train_loss = 0.642871
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 68 [0.40s]: train_loss = 0.638399
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 69 [0.40s]: train_loss = 0.634711
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 70 [0.42s]: train_loss = 0.629690
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 71 [0.40s]: train_loss = 0.624634
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 72 [0.41s]: train_loss = 0.619009
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 73 [0.41s]: train_loss = 0.614682
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 74 [0.41s]: train_loss = 0.608013
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 75 [0.40s]: train_loss = 0.602324
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 76 [0.54s]: train_loss = 0.596759
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 77 [0.40s]: train_loss = 0.589806
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 78 [0.41s]: train_loss = 0.582346
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 79 [0.52s]: train_loss = 0.575215
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 80 [0.44s]: train_loss = 0.568905
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 81 [0.44s]: train_loss = 0.561611
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 82 [0.42s]: train_loss = 0.553673
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 83 [0.42s]: train_loss = 0.548165
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 84 [0.43s]: train_loss = 0.541554
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 85 [0.55s]: train_loss = 0.532756
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 86 [0.40s]: train_loss = 0.523418
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 87 [0.42s]: train_loss = 0.517246
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 88 [0.41s]: train_loss = 0.511025
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 89 [0.40s]: train_loss = 0.503075
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 90 [0.39s]: train_loss = 0.494500
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 91 [0.39s]: train_loss = 0.488154
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 92 [0.39s]: train_loss = 0.479355
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 93 [0.39s]: train_loss = 0.472294
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 94 [0.53s]: train_loss = 0.470273
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 95 [0.39s]: train_loss = 0.458882
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 96 [0.38s]: train_loss = 0.454514
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 97 [0.39s]: train_loss = 0.447218
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 98 [0.40s]: train_loss = 0.445392
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 99 [0.41s]: train_loss = 0.440123
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 100 [0.42s]: train_loss = 0.438186

In [47]:
from recommenders.models.ncf.ncf_singlenode import NCF

mlp_dir = "checkpoints/mlp"

mlp = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="MLP",
    n_factors=1024,
    layer_sizes=[8],
    learning_rate=1e-3,
    batch_size=8192,
    n_epochs=100,
    verbose=1,
    seed=42
)

mlp.fit(dataset)
mlp.save(mlp_dir)

INFO:recommenders.models.ncf.ncf_singlenode:Epoch 1 [0.40s]: train_loss = 0.693083
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 2 [0.35s]: train_loss = 0.691911
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 3 [0.73s]: train_loss = 0.690900
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 4 [0.39s]: train_loss = 0.689848
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 5 [0.34s]: train_loss = 0.688829
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 6 [0.73s]: train_loss = 0.687863
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 7 [0.98s]: train_loss = 0.686707
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 8 [1.38s]: train_loss = 0.685730
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 9 [1.36s]: train_loss = 0.684654
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 10 [1.12s]: train_loss = 0.683546
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 11 [0.50s]: train_loss = 0.682489
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 12 [0.36s]: train_loss = 0.681523
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 13 [0.55s]: train_loss = 0.680441
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 14 [0.46s]: train_loss = 0.679420
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 15 [0.48s]: train_loss = 0.678404
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 16 [0.38s]: train_loss = 0.677033
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 17 [0.36s]: train_loss = 0.676238
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 18 [0.39s]: train_loss = 0.675164
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 19 [0.37s]: train_loss = 0.674029
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 20 [0.38s]: train_loss = 0.673033
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 21 [1.02s]: train_loss = 0.671728
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 22 [1.39s]: train_loss = 0.670833
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 23 [1.04s]: train_loss = 0.669592
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 24 [0.79s]: train_loss = 0.668743
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 25 [0.33s]: train_loss = 0.667619
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 26 [0.43s]: train_loss = 0.666490
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 27 [0.55s]: train_loss = 0.665503
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 28 [0.36s]: train_loss = 0.664394
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 29 [0.36s]: train_loss = 0.662966
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 30 [0.36s]: train_loss = 0.662095
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 31 [0.63s]: train_loss = 0.660501
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 32 [0.41s]: train_loss = 0.659785
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 33 [0.46s]: train_loss = 0.658638
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 34 [0.38s]: train_loss = 0.657214
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 35 [0.38s]: train_loss = 0.656221
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 36 [0.38s]: train_loss = 0.655045
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 37 [0.70s]: train_loss = 0.654055
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 38 [0.60s]: train_loss = 0.653174
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 39 [0.43s]: train_loss = 0.651981
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 40 [0.48s]: train_loss = 0.650974
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 41 [0.34s]: train_loss = 0.649586
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 42 [0.34s]: train_loss = 0.648349
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 43 [0.33s]: train_loss = 0.647306
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 44 [0.36s]: train_loss = 0.646061
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 45 [0.36s]: train_loss = 0.645347
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 46 [0.36s]: train_loss = 0.643346
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 47 [0.35s]: train_loss = 0.642782
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 48 [0.35s]: train_loss = 0.640184
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 49 [0.45s]: train_loss = 0.640177
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 50 [0.50s]: train_loss = 0.639154
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 51 [0.33s]: train_loss = 0.637578
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 52 [0.34s]: train_loss = 0.636964
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 53 [0.36s]: train_loss = 0.635385
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 54 [0.39s]: train_loss = 0.634171
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 55 [1.10s]: train_loss = 0.633485
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 56 [1.04s]: train_loss = 0.632232
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 57 [0.67s]: train_loss = 0.631255
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 58 [0.48s]: train_loss = 0.629876
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 59 [0.59s]: train_loss = 0.627363
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 60 [0.37s]: train_loss = 0.627238
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 61 [0.66s]: train_loss = 0.626537
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 62 [0.86s]: train_loss = 0.625319
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 63 [0.96s]: train_loss = 0.623542
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 64 [0.94s]: train_loss = 0.622701
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 65 [0.34s]: train_loss = 0.621390
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 66 [0.38s]: train_loss = 0.619679
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 67 [0.63s]: train_loss = 0.619152
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 68 [0.48s]: train_loss = 0.617326
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 69 [0.34s]: train_loss = 0.616552
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 70 [0.35s]: train_loss = 0.615167
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 71 [0.34s]: train_loss = 0.613754
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 72 [0.36s]: train_loss = 0.612719
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 73 [0.37s]: train_loss = 0.612599
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 74 [0.39s]: train_loss = 0.610265
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 75 [0.36s]: train_loss = 0.610029
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 76 [0.36s]: train_loss = 0.608709
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 77 [0.36s]: train_loss = 0.607560
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 78 [0.54s]: train_loss = 0.605407
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 79 [0.46s]: train_loss = 0.603194
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 80 [0.42s]: train_loss = 0.603439
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 81 [0.35s]: train_loss = 0.602650
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 82 [0.33s]: train_loss = 0.600014
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 83 [0.36s]: train_loss = 0.599861
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 84 [0.34s]: train_loss = 0.599673
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 85 [0.35s]: train_loss = 0.597331
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 86 [0.34s]: train_loss = 0.595115
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 87 [0.50s]: train_loss = 0.595000
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 88 [0.35s]: train_loss = 0.594593
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 89 [0.40s]: train_loss = 0.592566
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 90 [0.35s]: train_loss = 0.590627
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 91 [0.34s]: train_loss = 0.589980
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 92 [0.37s]: train_loss = 0.588655
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 93 [0.36s]: train_loss = 0.587436
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 94 [0.35s]: train_loss = 0.587590
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 95 [0.37s]: train_loss = 0.584791
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 96 [0.49s]: train_loss = 0.584837
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 97 [0.36s]: train_loss = 0.582488
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 98 [0.35s]: train_loss = 0.582687
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 99 [0.34s]: train_loss = 0.581547
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 100 [0.33s]: train_loss = 0.581156

In [48]:
neucf = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="NeuMF",
    n_factors=1024,
    layer_sizes=[8],
    learning_rate=1e-2,
    batch_size=8192,
    n_epochs=100,
    verbose=1,
    seed=42
)

In [49]:
neucf._load_neumf(
    gmf_dir=gmf_dir,
    mlp_dir=mlp_dir,
    alpha=0.5
)

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/mlp\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/mlp\model.ckpt

In [50]:
neucf.fit(dataset)

INFO:recommenders.models.ncf.ncf_singlenode:Epoch 1 [0.62s]: train_loss = 0.485600
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 2 [0.42s]: train_loss = 0.444198
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 3 [0.42s]: train_loss = 0.418623
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 4 [0.40s]: train_loss = 0.402259
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 5 [0.58s]: train_loss = 0.399731
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 6 [0.45s]: train_loss = 0.397691
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 7 [1.17s]: train_loss = 0.389651
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 8 [1.27s]: train_loss = 0.395104
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 9 [1.53s]: train_loss = 0.385964
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 10 [0.64s]: train_loss = 0.375484
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 11 [0.48s]: train_loss = 0.366663
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 12 [0.60s]: train_loss = 0.352669
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 13 [0.43s]: train_loss = 0.335095
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 14 [0.80s]: train_loss = 0.316375
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 15 [0.55s]: train_loss = 0.305930
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 16 [0.42s]: train_loss = 0.286557
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 17 [0.41s]: train_loss = 0.277793
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 18 [0.43s]: train_loss = 0.261972
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 19 [0.42s]: train_loss = 0.252818
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 20 [0.39s]: train_loss = 0.236441
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 21 [0.42s]: train_loss = 0.226065
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 22 [0.41s]: train_loss = 0.211183
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 23 [0.53s]: train_loss = 0.197802
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 24 [0.40s]: train_loss = 0.181398
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 25 [0.41s]: train_loss = 0.166163
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 26 [0.40s]: train_loss = 0.151693
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 27 [0.40s]: train_loss = 0.138322
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 28 [0.40s]: train_loss = 0.121536
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 29 [0.39s]: train_loss = 0.105935
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 30 [0.42s]: train_loss = 0.091303
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 31 [0.40s]: train_loss = 0.080151
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 32 [0.41s]: train_loss = 0.070128
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 33 [1.41s]: train_loss = 0.061289
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 34 [1.57s]: train_loss = 0.052245
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 35 [1.18s]: train_loss = 0.046143
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 36 [0.61s]: train_loss = 0.038617
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 37 [0.44s]: train_loss = 0.034145
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 38 [0.52s]: train_loss = 0.030221
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 39 [0.61s]: train_loss = 0.026703
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 40 [0.50s]: train_loss = 0.023665
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 41 [0.49s]: train_loss = 0.020604
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 42 [0.84s]: train_loss = 0.018413
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 43 [0.46s]: train_loss = 0.015500
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 44 [0.46s]: train_loss = 0.013622
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 45 [0.48s]: train_loss = 0.013527
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 46 [0.68s]: train_loss = 0.011674
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 47 [0.64s]: train_loss = 0.010724
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 48 [0.51s]: train_loss = 0.010301
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 49 [0.41s]: train_loss = 0.010183
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 50 [0.42s]: train_loss = 0.008486
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 51 [0.57s]: train_loss = 0.008733
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 52 [0.41s]: train_loss = 0.008771
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 53 [0.40s]: train_loss = 0.007427
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 54 [0.41s]: train_loss = 0.006955
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 55 [0.41s]: train_loss = 0.006253
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 56 [0.43s]: train_loss = 0.006557
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 57 [0.41s]: train_loss = 0.006884
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 58 [0.41s]: train_loss = 0.005842
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 59 [0.42s]: train_loss = 0.006192
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 60 [0.43s]: train_loss = 0.005912
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 61 [0.62s]: train_loss = 0.005915
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 62 [0.43s]: train_loss = 0.005555
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 63 [0.41s]: train_loss = 0.005438
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 64 [0.42s]: train_loss = 0.006633
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 65 [0.42s]: train_loss = 0.005368
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 66 [0.61s]: train_loss = 0.004819
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 67 [0.87s]: train_loss = 0.004577
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 68 [1.06s]: train_loss = 0.005379
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 69 [1.15s]: train_loss = 0.004702
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 70 [1.14s]: train_loss = 0.004761
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 71 [0.41s]: train_loss = 0.004128
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 72 [0.42s]: train_loss = 0.004619
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 73 [0.53s]: train_loss = 0.004256
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 74 [0.71s]: train_loss = 0.004255
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 75 [0.44s]: train_loss = 0.005469
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 76 [0.43s]: train_loss = 0.004511
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 77 [0.90s]: train_loss = 0.004600
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 78 [1.06s]: train_loss = 0.004538
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 79 [1.04s]: train_loss = 0.004403
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 80 [0.42s]: train_loss = 0.004458
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 81 [0.43s]: train_loss = 0.004085
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 82 [0.70s]: train_loss = 0.004294
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 83 [0.60s]: train_loss = 0.004217
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 84 [0.48s]: train_loss = 0.004106
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 85 [0.42s]: train_loss = 0.003991
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 86 [0.43s]: train_loss = 0.003474
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 87 [0.42s]: train_loss = 0.004138
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 88 [0.58s]: train_loss = 0.003663
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 89 [0.43s]: train_loss = 0.004374
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 90 [0.45s]: train_loss = 0.003635
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 91 [0.45s]: train_loss = 0.004050
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 92 [0.47s]: train_loss = 0.003204
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 93 [0.44s]: train_loss = 0.003336
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 94 [0.43s]: train_loss = 0.003502
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 95 [0.41s]: train_loss = 0.003587
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 96 [0.43s]: train_loss = 0.004250
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 97 [0.93s]: train_loss = 0.004227
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 98 [1.05s]: train_loss = 0.003645
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 99 [0.86s]: train_loss = 0.003455
INFO:recommenders.models.ncf.ncf_singlenode:Epoch 100 [0.85s]: train_loss = 0.003774

In [51]:
neucf.save("checkpoints/neucf")

# Generate predictions

In [1]:
import numpy as np
import pandas as pd

from recommenders.models.ncf.ncf_singlenode import NCF
from recommenders.models.ncf.dataset import Dataset

WARNING:tensorflow:From c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\recommenders\models\ncf\ncf_singlenode.py:12: The name tf.disable_eager_execution is deprecated. Please use tf.compat.v1.disable_eager_execution instead.

In [6]:
dataset = Dataset(
    train_file="train.csv",
    test_file="test.csv",
    n_neg=4,
    n_neg_test=100,
    col_user="userID",
    col_item="itemID",
    col_rating="label",
    binary=True,
    seed=42
)

INFO:recommenders.models.ncf.dataset:Indexing train.csv ...
INFO:recommenders.models.ncf.dataset:Indexing test.csv ...
INFO:recommenders.models.ncf.dataset:Indexing test_full.csv ...

In [3]:
gmf = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="GMF",
    n_factors=1024,
    learning_rate=1e-3,
    batch_size=8192,
    n_epochs=100,
    verbose=0
)
gmf.load("checkpoints/gmf")

WARNING:tensorflow:From c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\recommenders\models\ncf\ncf_singlenode.py:269: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1697: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
WARNING:tensorflow:From c:\Users\lebro\OneDrive - Nanyang Technological University\Github\YelpFYP\venv\lib\site-packages\recommenders\models\ncf\ncf_singlenode.py:269: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

In [7]:
mlp = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="MLP",
    n_factors=1024,
    layer_sizes=[8],
    learning_rate=1e-3,
    batch_size=8192,
    n_epochs=100,
    verbose=0,
    seed=42
)

mlp.fit(dataset)

In [8]:
neucf = NCF(
    n_users=dataset.n_users,
    n_items=dataset.n_items,
    model_type="NeuMF",
    n_factors=1024,
    layer_sizes=[8],
    learning_rate=1e-2,   # Appendix A.1.3
    batch_size=8192,
    n_epochs=100,
    verbose=0,
    seed=42
)

neucf.load(
    gmf_dir="checkpoints/gmf",
    mlp_dir="checkpoints/mlp",
    alpha=0.5
)

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/gmf\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/mlp\model.ckpt

INFO:tensorflow:Restoring parameters from checkpoints/mlp\model.ckpt

In [11]:
def attach_dataset_mappings(model, dataset):
    model.user2id = dataset.user2id
    model.item2id = dataset.item2id
    model.id2user = dataset.id2user
    model.id2item = dataset.id2item

attach_dataset_mappings(gmf, dataset)
attach_dataset_mappings(mlp, dataset)
attach_dataset_mappings(neucf, dataset)

In [17]:
import numpy as np

def evaluate_ncf(model, dataset, k=10):
    hits, ndcgs = [], []

    for users, items, labels in dataset.test_loader(yield_id=False):
        scores = model.predict(users, items, is_list=True)

        scores = np.array(scores)
        labels = np.array(labels)

        # rank items by score
        order = np.argsort(scores)[::-1]
        ranked_labels = labels[order][:k]

        # HR@k
        hit = int(ranked_labels.sum() > 0)
        hits.append(hit)

        # NDCG@k
        if hit:
            pos = np.where(ranked_labels == 1)[0][0]
            ndcgs.append(1 / np.log2(pos + 2))
        else:
            ndcgs.append(0)

    hr = np.mean(hits)
    ndcg = np.mean(ndcgs)

    # Recall@10 == HR@10 in leave-one-out
    return hr, hr, ndcg

In [18]:
results = []

for name, model in [
    ("GMF", gmf),
    ("MLP", mlp),
    ("NeuCF", neucf),
]:
    p, r, n = evaluate_ncf(model, dataset, k=10)
    results.append({
        "Model": name,
        "Precision@10": round(p, 4),
        "Recall@10": round(r, 4),
        "NDCG@10": round(n, 4),
    })

table_5_1 = pd.DataFrame(results)
table_5_1

   Model  Precision@10  Recall@10  NDCG@10
0    GMF        0.2500     0.2500   0.1329
1    MLP        0.2639     0.2639   0.1322
2  NeuCF        0.2535     0.2535   0.1337

# Sanity Check

In [23]:
from recommenders.models.ncf.dataset import Dataset

dataset = Dataset(
    train_file="train.csv",
    test_file="test.csv",          # leave-one-out positives
    test_file_full="test_full.csv",# auto-generated negatives
    n_neg_test=100,
    col_user="userID",
    col_item="itemID",
    col_rating="label",
    binary=True,
    seed=42
)

INFO:recommenders.models.ncf.dataset:Indexing train.csv ...
INFO:recommenders.models.ncf.dataset:Indexing test.csv ...
INFO:recommenders.models.ncf.dataset:Indexing test_full.csv ...

In [24]:
users, items, labels = next(dataset.test_loader(yield_id=False))

print(len(users))          # MUST be 101
print(sum(labels))         # MUST be 1

101
1.0

In [25]:
import numpy as np

def evaluate_ncf(model, dataset, k=10):
    precisions, recalls, ndcgs = [], [], []

    for users, items, labels in dataset.test_loader(yield_id=False):
        scores = []
        for u, i in zip(users, items):
            scores.append(model.predict(u, i))

        scores = np.array(scores)
        labels = np.array(labels)

        topk = np.argsort(scores)[::-1][:k]
        hits = labels[topk]

        precisions.append(hits.sum() / k)
        recalls.append(1.0 if hits.sum() > 0 else 0.0)

        if hits.sum() > 0:
            rank = np.where(hits == 1)[0][0] + 1
            ndcgs.append(1 / np.log2(rank + 1))
        else:
            ndcgs.append(0.0)

    return np.mean(precisions), np.mean(recalls), np.mean(ndcgs)

In [26]:
results = []

for name, model in [
    ("GMF", gmf),
    ("MLP", mlp),
    ("NeuCF", neucf),
]:
    p, r, n = evaluate_ncf(model, dataset, k=10)
    results.append({
        "Model": name,
        "Precision@10": round(p, 4),
        "Recall@10": round(r, 4),
        "NDCG@10": round(n, 4),
    })

table_5_1 = pd.DataFrame(results)
table_5_1

   Model  Precision@10  Recall@10  NDCG@10
0    GMF        0.0250     0.2500   0.1329
1    MLP        0.0264     0.2639   0.1322
2  NeuCF        0.0253     0.2535   0.1337